In [1]:
import numpy as np
import pandas as pd

# Часть 1. Python

In [316]:
#Напишите функцию, которая вычленяет из текста все числа и возвражает их списком

def take_numb(my_string):
  #Your code here
    lis = ''.join([c for c in my_string if c.isalnum() or c.isspace()]).split()
    num_list = [int(num) for num in filter(lambda num: num.isnumeric() , lis)]
    return print(num_list)


take_numb('I was born in 1998')  #[1998]
take_numb('She had got 5 cats and 3 kittens') #[5, 3]
take_numb('Does it really cost 500$? Or maybe 450$?') #[500, 450]

[1998]
[5, 3]
[500, 450]

In [318]:
#Напишите функцию, которая принимает на вход словарь, а возвращает все уникальные значения словаря списком

def get_distinct_dic(dic):
  #Your code here
    orig_list = list(set([int(num) for num in dic.values()])) 
    return orig_list
    
    

get_distinct_dic({'jan':47, 'feb':52, 'march':47, 'April':44, 'May':52, 'June':53, 'july':54, 'Aug':44, 'Sept':54}) # [47, 52, 44, 53, 54]

[52, 44, 53, 54, 47]

In [323]:
#Напишите функцию, которая принимает на вход список, а возвращает все уникальные 
#значения списка + печатает минимум и максимум списка

def get_distinct_list(dic):
  #Your code here
    dic.sort()
    return list(set(dic)), dic[0], dic[-1] 

get_distinct_list([9123, 31, 1938, 9123, 1, 249, 912, 10, 31, 213, 81, 10]) # [31, 1938, 9123, 1, 249, 912, 010, 213, 81], min = 1, max = 9123

([1, 9123, 10, 912, 81, 1938, 213, 249, 31], 1, 9123)

In [671]:
#Выведите сколько раз в тексте встречается каждое слово (не учитывая регистр), каждый знак преминания и каждая буква

sample_test = "Гостиная Анны Павловны начала понемногу наполняться. Приехала высшая знать Петербурга, люди самые разнородные по возрастам и характерам, но одинаковые по обществу, в каком все жили; приехала дочь князя Василия, красавица Элен, заехавшая за отцом, чтобы с ним вместе ехать на праздник посланника. Она была в шифре и бальном платье. Приехала и известная, как la femme la plus séduisante de Pétersbourg 1, молодая, маленькая княгиня Болконская, прошлую зиму вышедшая замуж и теперь не выезжавшая в большой свет по причине своей беременности, но ездившая еще на небольшие вечера. Приехал князь Ипполит, сын князя Василия, с Мортемаром, которого он представил; приехал и аббат Морио и многие другие. — Вы не видали еще, — или: — вы не знакомы с ma tante? 2 — говорила Анна Павловна приезжавшим гостям и весьма серьезно подводила их к маленькой старушке в высоких бантах, выплывшей из другой комнаты, как скоро стали приезжать гости, называла их по имени, медленно переводя глаза с гостя на ma tante, и потом отходила. Все гости совершали обряд приветствования никому не известной, никому не интересной и не нужной тетушки. Анна Павловна с грустным, торжественным участием следила за их приветствиями, молчаливо одобряя их. Ma tante каждому говорила в одних и тех же выражениях о его здоровье, о своем здоровье и о здоровье ее величества, которое нынче было, слава Богу, лучше. Все подходившие, из приличия не выказывая поспешности, с чувством облегчения исполненной тяжелой обязанности отходили от старушки, чтоб уж весь вечер ни разу не подойти к ней. Молодая княгиня Болконская приехала с работой в шитом золотом бархатном мешке. Ее хорошенькая, с чуть черневшимися усиками верхняя губка была коротка по зубам, но тем милее она открывалась и тем еще милее вытягивалась иногда и опускалась на нижнюю. Как это бывает у вполне привлекательных женщин, недостаток ее — короткость губы и полуоткрытый рот — казались ее особенною, собственно ее красотой. Всем было весело смотреть на эту полную здоровья и живости хорошенькую будущую мать, так легко переносившую свое положение. Старикам и скучающим, мрачным молодым людям казалось, что они сами делаются похожи на нее, побыв и поговорив несколько времени с ней. Кто говорил с ней и видел при каждом слове ее светлую улыбочку и блестящие белые зубы, которые виднелись беспрестанно, тот думал, что он особенно нынче любезен. И это думал каждый."
arra = sample_test.lower()

#считаю сколько раз встречаются буквы и знаки
d_1 = dict((i, arra.count(i)) for i in set(list(arra)))

#считаю сколько раз встречаются слова
array = ''.join([c for c in arra if c.isalnum() or c.isspace()]).split()
d = dict((x, array.count(x)) for x in set(array))

#for i in set(array):
#    print('слово '+ i + ' встречается ' + str(d[i]) )
for i in set(arra):
    print('символ ' + i +  ' встречается ' +str(d_1[i]) )
#print(d)
#print(d_1)

символ ь встречается 34
символ й встречается 18
символ   встречается 369
символ б встречается 39
символ l встречается 3
символ в встречается 94
символ b встречается 1
символ e встречается 8
символ ч встречается 23
символ o встречается 1
символ 1 встречается 1
символ я встречается 48
символ t встречается 8
символ r встречается 2
символ g встречается 1
символ p встречается 2
символ s встречается 4
символ и встречается 139
символ у встречается 44
символ ю встречается 14
символ о встречается 201
символ : встречается 1
символ i встречается 1
символ ; встречается 2
символ л встречается 89
символ а встречается 154
символ . встречается 17
символ з встречается 37
символ п встречается 52
символ ы встречается 44
символ т встречается 96
символ р встречается 77
символ ? встречается 1
символ d встречается 2
символ н встречается 131
символ д встречается 43
символ ф встречается 1
символ ш встречается 25
символ , встречается 41
символ u встречается 3
символ щ встречается 8
символ n встречается 4
символ к встречается 67
символ f встречается 1
символ м встречается 65
символ é встречается 2
символ m встречается 5
символ 2 встречается 1
символ э встречается 4
символ a встречается 9
символ — встречается 6
символ е встречается 172
символ ц встречается 2
символ ж встречается 19
символ с встречается 93
символ х встречается 27
символ г встречается 27

# Часть 2. Numpy

In [272]:
#Реализуйте функции, которые будут считать следующие расстояние между векторами:
a = np.array((9,4,8))
b = np.array((3,4,0))

#1. Евклидово расстояние
def evklid_dist(arr_a,arr_b):
    assert len(arr_a) == len(arr_b)
    
    dist = np.sqrt(np.sum((arr_a-arr_b)**2))
    return dist



#2. Хеммингово расстояние
def hamming_dist(arr_a, arr_b):
    assert len(arr_a) == len(arr_b)
    
    dist = sum([abs(arr_a[i] - arr_b[i]) for i in range(len(arr_b))])
    return dist



#3. Расстояние Чебышева
def cheb_dist(arr_a, arr_b):
    assert len(arr_a) == len(arr_b)
    
    dist = max([abs(arr_a[i] - arr_b[i]) for i in range(len(arr_b))])
    return dist


print(evklid_dist(a,b))
print(hamming_dist(a,b))
print(cheb_dist(a,b))
# Вектора в функцию подаются как numpy.array.

10.0
14
8

# Часть 3. Pandas

In [28]:
#Считайте датасет из файла train.csv - это данные о выживаемости на Титанике
df = pd.read_csv("train.csv")
#df.Name.head(100)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 66.2+ KB

In [677]:
#Выведите основную информацию о датасете - число пропусков, средние значения и т.д. 
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [83]:
#Посчитайте процент выживаемости у каждого класса пассажиров (Pclass) 
pr= df.groupby('Pclass').Survived.sum()* 100 / df.groupby('Pclass').Survived.count()
#pr[3]

print('1-ом классе = ' '%.3f' % float(pr[1]) )
print('2-ом классе = ' '%.3f' % float(pr[2]) )
print('3-ем классе = ' '%.3f' % float(pr[3]) )

1-ом классе = 62.963
2-ом классе = 47.283
3-ем классе = 24.236

In [82]:
#Посчитайте процнт выживаемости для мужчин и женщин
proc = df.groupby('Sex').Survived.sum() * 100 / df.groupby('Sex').Survived.count()

print('Мужчин = ' '%.3f' % float(proc[1]) )
print('Женщин = ' '%.3f' % float(proc[0]) )

Мужчин = 18.891
Женщин = 74.204

In [85]:
#Выведите самое популярное мужское и самое популярное женское имя на корабле
df.Sal = df['Name'].apply(lambda name: name.split(',')[1].split('.')[0].strip())

df['man'] = df.loc[df['Sex'] == 'male' ]['Name'].apply(lambda s: s.split('.')[1].split(' ')[1]) 
df['man'].value_counts()

df.mrs = df.loc[df.Sal.isin(['Mrs'])]['Name'].apply(lambda s: s.split('.')[1])
df.mrs.values

#arr_n = df.mrs.values
#arr = [i for i in arr_n if len(i) > 1 ]
#arr
#df.mrs


#d = dict((x, arr.count(x)) for x in set(list(arr)) if arr.count(x)> 2)
#print(d)
#df.groupby('Pclass').

array([' John Bradley (Florence Briggs Thayer)',
       ' Jacques Heath (Lily May Peel)',
       ' Oscar W (Elisabeth Vilhelmina Berg)', ' Nicholas (Adele Achem)',
       ' (Mary D Kingcome) ', ' Julius (Emelia Maria Vandemoortele)',
       ' Fatima', ' Carl Oscar (Selma Augusta Emilia Johansson)',
       ' William Augustus (Marie Eugenie)',
       ' Johan (Johanna Persdotter Larsson)',
       ' William John Robert (Dorothy Ann Wonnacott)',
       ' Josef (Josefine Franchi)', ' Henry Sleeper (Myna Haxtun)',
       ' Lizzie (Elizabeth Anne Wilkinson)', ' (Elizabeth Ramell)',
       ' Karl Alfred (Maria Mathilda Gustafsson)',
       ' John T (Ada Julia Bone)', ' Alexander A (Grace Charity Laury)',
       ' Leopold (Mathilde Francoise Pede)', ' Joseph (Sultana)',
       ' Pekka Pietari (Elin Matilda Dolck)', ' Thomas (Edith Wearne)',
       ' James (Elizabeth "Bessie" Inglis Milne)',
       ' (Edith Martha Bowerman)', ' William (Anna Bernhardina Karlsson)',
       ' Thomas (Johanna "Hannah" Godfrey)', ' (Rosa)',
       ' James Joseph (Margaret Tobin)',
       ' Henry Birkhardt (Irene Wallach)', ' William (Anna)',
       ' Wilhelm (Elna Matilda Persson)', ' Viktor (Helena Wilhelmina)',
       ' Darwis (Hanne Youssef Razi)', ' Gertrude Maybelle',
       ' (Lutie Davis)', ' William Thompson (Edith Junkins)',
       ' (Elizabeth Anne Maidment)', ' Stanton (Rosa Hunt)',
       ' Dickinson H (Helen Walton)',
       ' James (Helene DeLaudeniere Chaput)',
       ' Victor de Satode (Maria Josefa Perez de Soto y Vallejo)',
       ' William (Anna Sylfven)', ' Sinai (Miriam Sternin)',
       ' Frederic Oakley (Margaretta Corning Stone)',
       ' Albert Francis (Sylvia Mae Harbaugh)', ' (Ada E Hall)',
       ' Frank John (Emily Alice Brown)',
       ' Henry William (Clara Heinsheimer)',
       ' Thomas Henry (Mary E Finck)', ' (Catherine David)',
       ' Frank Manley (Anna Sophia Atkinson)', ' (Mantoura Boulos)',
       ' Edgar Joseph (Leila Saks)',
       ' Alexander Oskar (Mary Aline Towner)',
       ' Hjalmar (Agnes Charlotta Bengtsson)', ' William H (Jessie L)',
       ' Thomas (Annie Louise Rowley)',
       ' James Vivian (Lulu Thorne Christian)',
       ' Ernst Gilbert (Anna Sigrid Maria Brogren)',
       ' Charles V (Ada Maria Winfield)',
       ' Percival (Florence Kate White)',
       ' Charles Alexander (Alice Adelaide Slow)',
       ' Sidney (Emily Hocking)', ' Benjamin (Esther Ada Bloomfield)',
       ' Frederick R (Marion)', ' Edwy Arthur (Ada Mary Worth)',
       ' Amin S (Marie Marthe Thuillard)', ' (Hedwig)',
       ' Frederick Maxfield (Jane Anne Forby)',
       ' Hudson J C (Bessie Waldo Daniels)',
       ' Frederick Charles (Jane Richards)', ' Martin (Elizabeth L',
       ' (Amelia Milley)', ' William A (Florence "Mary" Agnes Hughes)',
       ' Louis Albert (Ida Sophia Fischer)',
       ' Catherine (Catherine Rizk)', ' Edward (Ethel Clarke)',
       ' Emil (Tillie Mandelbaum)', ' Guillaume Joseph (Emma)',
       ' Nils (Alma Cornelia Berglund)',
       ' Edward Dale (Charlotte Lamson)', ' William Baird (Alice Munger)',
       ' Joseph (Maria Elias)',
       ' John Borland (Marian Longstreth Morris)',
       ' Walter Bertram (Martha Eustis)',
       ' Sidney Samuel (Amy Frances Christy)',
       ' Joseph (Juliette Marie Louise Lafargue)',
       ' Anders Johan (Alfrida Konstantia Brogren)',
       ' William Arthur (Cordelia K Stanlick)',
       ' Juha (Maria Emilia Ojala)', ' John (Catherine)',
       ' Elmer Zebley (Juliet Cummins Wright)',
       ' Thomas William Solomon (Elizabeth Catherine Ford)',
       ' Frederick (Augusta Tyler)',
       ' John Jacob (Madeleine Talmadge Force)', ' Florence "Fannie"',
       ' Peter Henry (Lillian Jefferys)', ' Edward (Margaret Ann Watson)',
       ' Samuel (Jane Laver)', ' William Ernest (Lucile Polk)',
       ' John C (Anna Andrews)', ' (Mary)', ' Elizabeth (Eliza Needs)',
       ' Edward Scott (Elisabeth Walton McMillan)',
       ' Albert Adrian (Vera Gillespie)', ' Mara',
       ' Jean Baptiste (Rosalie Paula Govaert)',
       ' Harvey (Charlotte Annie Tate)',
       ' Norman Campbell (Bertha Griggs)',
       ' Charles Melville (Clara Jennings Gregg)', ' (Beila)',
       ' George Nelson (Martha Evelyn)', ' Antoni (Selini Alexander)',
       ' Samuel L (Edwiga Grabowska)',
       ' Ernest Courtenay (Lilian Hughes)', ' Sam (Leah Rosen)',
       ' George Dennick (Mary Hitchcock)', ' Solomon (Latifa Qurban)',
       ' Frederick Joel (Margaret Welles Barron)', ' (Karolina)',
       ' Richard Leonard (Sallie Monypeny)', ' Samuel (Hannah Wizosky)',
       ' Thomas Jr (Lily Alexenia Wilson)',
       ' William (Imanita Parrish Hall)', ' William (Margaret Norton)'],
      dtype=object)

In [577]:
#Выведите самое популярное мужское и самое популярное женское имя на корабле в каждом классе

In [666]:
#Выведите количества n-местных кабин (в которых было 2, 3, 4, ... человека)

arr_cab = df.Cabin.values
arr = [i for i in arr_cab if i is not np.nan]                      # убираю все nan из массива
d = dict((x, arr.count(x)) for x in set(arr) if arr.count(x) > 1)
arr_l = list(d.values())
dic = dict((x, arr_l.count(x)) for x in set(arr_l))
#arr.value_counts()

print(dic)

{2: 38, 3: 5, 4: 3}

In [491]:
#Выведите часть таблицы с пассажирами, возраст которых больше 44 лет.
df.loc[df.Age > 44]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,D33,C
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
62,63,0,1,"Harris, Mr. Henry Birkhardt",male,45.0,1,0,36973,83.4750,C83,S
92,93,0,1,"Chaffee, Mr. Herbert Fuller",male,46.0,1,0,W.E.P. 5734,61.1750,E31,S
94,95,0,3,"Coxon, Mr. Daniel",male,59.0,0,0,364500,7.2500,NaN,S
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
110,111,0,1,"Porter, Mr. Walter Chamberlain",male,47.0,0,0,110465,52.0000,C110,S
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
124,125,0,1,"White, Mr. Percival Wayland",male,54.0,0,1,35281,77.2875,D26,S
129,130,0,3,"Ekstrom, Mr. Johan",male,45.0,0,0,347061,6.9750,NaN,S
132,133,0,3,"Robins, Mrs. Alexander A (Grace Charity Laury)",female,47.0,1,0,A/5. 3337,14.5000,NaN,S
150,151,0,2,"Bateman, Rev. Robert James",male,51.0,0,0,S.O.P. 1166,12.5250,NaN,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C
167,168,0,3,"Skoog, Mrs. William (Anna Bernhardina Karlsson)",female,45.0,1,4,347088,27.9000,NaN,S
170,171,0,1,"Van der hoef, Mr. Wyckoff",male,61.0,0,0,111240,33.5000,B19,S
174,175,0,1,"Smith, Mr. James Clinch",male,56.0,0,0,17764,30.6958,A7,C
177,178,0,1,"Isham, Miss. Ann Elizabeth",female,50.0,0,0,PC 17595,28.7125,C49,C
187,188,1,1,"Romaine, Mr. Charles Hallace (""Mr C Rolmane"")",male,45.0,0,0,111428,26.5500,NaN,S
195,196,1,1,"Lurette, Miss. Elise",female,58.0,0,0,PC 17569,146.5208,B80,C
203,204,0,3,"Youseff, Mr. Gerious",male,45.5,0,0,2628,7.2250,NaN,C
222,223,0,3,"Green, Mr. George Henry",male,51.0,0,0,21440,8.0500,NaN,S
232,233,0,2,"Sjostedt, Mr. Ernst Adolf",male,59.0,0,0,237442,13.5000,NaN,S
249,250,0,2,"Carter, Rev. Ernest Courtenay",male,54.0,1,0,244252,26.0000,NaN,S
252,253,0,1,"Stead, Mr. William Thomas",male,62.0,0,0,113514,26.5500,C87,S
259,260,1,2,"Parrish, Mrs. (Lutie Davis)",female,50.0,0,1,230433,26.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
659,660,0,1,"Newell, Mr. Arthur Webster",male,58.0,0,2,35273,113.2750,D48,C
660,661,1,1,"Frauenthal, Dr. Henry William",male,50.0,2,0,PC 17611,133.6500,NaN,S
662,663,0,1,"Colley, Mr. Edward Pomeroy",male,47.0,0,0,5727,25.5875,E58,S
672,673,0,2,"Mitchell, Mr. Henry Michael",male,70.0,0,0,C.A. 24580,10.5000,NaN,S
684,685,0,2,"Brown, Mr. Thomas William Solomon",male,60.0,1,1,29750,39.0000,NaN,S
694,695,0,1,"Weir, Col. John",male,60.0,0,0,113800,26.5500,NaN,S
695,696,0,2,"Chapman, Mr. Charles Henry",male,52.0,0,0,248731,13.5000,NaN,S
698,699,0,1,"Thayer, Mr. John Borland",male,49.0,1,1,17421,110.8833,C68,C
706,707,1,2,"Kelly, Mrs. Florence ""Fannie""",female,45.0,0,0,223596,13.5000,NaN,S
712,713,1,1,"Taylor, Mr. Elmer Zebley",male,48.0,1,0,19996,52.0000,C126,S
714,715,0,2,"Greenberg, Mr. Samuel",male,52.0,0,0,250647,13.0000,NaN,S
723,724,0,2,"Hodges, Mr. Henry Price",male,50.0,0,0,250643,13.0000,NaN,S
736,737,0,3,"Ford, Mrs. Edward (Margaret Ann Watson)",female,48.0,1,3,W./C. 6608,34.3750,NaN,S
745,746,0,1,"Crosby, Capt. Edward Gifford",male,70.0,1,1,WE/P 5735,71.0000,B22,S
754,755,1,2,"Herman, Mrs. Samuel (Jane Laver)",female,48.0,1,2,220845,65.0000,NaN,S
765,766,1,1,"Hogeboom, Mrs. John C (Anna Andrews)",female,51.0,1,0,13502,77.9583,D11,S
771,772,0,3,"Jensen, Mr. Niels Peder",male,48.0,0,0,350047,7.8542,NaN,S
772,773,0,2,"Mack, Mrs. (Mary)",female,57.0,0,0,S.O./P.P. 3,10.5000,E77,S
774,775,1,2,"Hocking, Mrs. Elizabeth (Eliza Needs)",female,54.0,1,3,29105,23.0000,NaN,S
789,790,0,1,"Guggenheim, Mr. Benjamin",male,46.0,0,0,PC 17593,79.2000,B82 B84,C
796,797,1,1,"Leader, Dr. Alice (Farnham)",female,49.0,0,0,17465,25.9292,D17,S
820,821,1,1,"Hays, Mrs. Charles Melville (Clara Jennings Gr...",female,52.0,1,1,12749,93.5000,B69,S
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0000,B28,NaN
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.0,1,1,36928,164.8667,NaN,S
857,858,1,1,"Daly, Mr. Peter Denis",male,51.0,0,0,113055,26.5500,E17,S
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,D17,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,9.0000,NaN,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C

In [490]:
#Выведите часть таблицы с пассажирами, возраст которых меньше 44 лет и которые мужского пола.
df.loc[(df.Sex == 'male') & (df.Age < 44)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.00,1,0,A/5 21171,7.2500,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.00,0,0,373450,8.0500,NaN,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.00,3,1,349909,21.0750,NaN,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.00,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.00,1,5,347082,31.2750,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.00,4,1,382652,29.1250,NaN,Q
20,21,0,2,"Fynney, Mr. Joseph J",male,35.00,0,0,239865,26.0000,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.00,0,0,248698,13.0000,D56,S
23,24,1,1,"Sloper, Mr. William Thompson",male,28.00,0,0,113788,35.5000,A6,S
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.00,3,2,19950,263.0000,C23 C25 C27,S
30,31,0,1,"Uruchurtu, Don. Manuel E",male,40.00,0,0,PC 17601,27.7208,NaN,C
34,35,0,1,"Meyer, Mr. Edgar Joseph",male,28.00,1,0,PC 17604,82.1708,NaN,C
35,36,0,1,"Holverson, Mr. Alexander Oskar",male,42.00,1,0,113789,52.0000,NaN,S
37,38,0,3,"Cann, Mr. Ernest Charles",male,21.00,0,0,A./5. 2152,8.0500,NaN,S
50,51,0,3,"Panula, Master. Juha Niilo",male,7.00,4,1,3101295,39.6875,NaN,S
51,52,0,3,"Nosworthy, Mr. Richard Cater",male,21.00,0,0,A/4. 39886,7.8000,NaN,S
57,58,0,3,"Novel, Mr. Mansouer",male,28.50,0,0,2697,7.2292,NaN,C
59,60,0,3,"Goodwin, Master. William Frederick",male,11.00,5,2,CA 2144,46.9000,NaN,S
60,61,0,3,"Sirayanian, Mr. Orsen",male,22.00,0,0,2669,7.2292,NaN,C
63,64,0,3,"Skoog, Master. Harald",male,4.00,3,2,347088,27.9000,NaN,S
67,68,0,3,"Crease, Mr. Ernest James",male,19.00,0,0,S.P. 3464,8.1583,NaN,S
69,70,0,3,"Kink, Mr. Vincenz",male,26.00,2,0,315151,8.6625,NaN,S
70,71,0,2,"Jenkin, Mr. Stephen Curnow",male,32.00,0,0,C.A. 33111,10.5000,NaN,S
72,73,0,2,"Hood, Mr. Ambrose Jr",male,21.00,0,0,S.O.C. 14879,73.5000,NaN,S
73,74,0,3,"Chronopoulos, Mr. Apostolos",male,26.00,1,0,2680,14.4542,NaN,C
74,75,1,3,"Bing, Mr. Lee",male,32.00,0,0,1601,56.4958,NaN,S
75,76,0,3,"Moen, Mr. Sigurd Hansen",male,25.00,0,0,348123,7.6500,F G73,S
78,79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S
80,81,0,3,"Waelens, Mr. Achille",male,22.00,0,0,345767,9.0000,NaN,S
81,82,1,3,"Sheerlinck, Mr. Jan Baptist",male,29.00,0,0,345779,9.5000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
824,825,0,3,"Panula, Master. Urho Abraham",male,2.00,4,1,3101295,39.6875,NaN,S
827,828,1,2,"Mallet, Master. Andre",male,1.00,0,2,S.C./PARIS 2079,37.0042,NaN,C
831,832,1,2,"Richards, Master. George Sibley",male,0.83,1,1,29106,18.7500,NaN,S
833,834,0,3,"Augustsson, Mr. Albert",male,23.00,0,0,347468,7.8542,NaN,S
834,835,0,3,"Allum, Mr. Owen George",male,18.00,0,0,2223,8.3000,NaN,S
836,837,0,3,"Pasic, Mr. Jakob",male,21.00,0,0,315097,8.6625,NaN,S
838,839,1,3,"Chip, Mr. Chang",male,32.00,0,0,1601,56.4958,NaN,S
840,841,0,3,"Alhomaki, Mr. Ilmari Rudolf",male,20.00,0,0,SOTON/O2 3101287,7.9250,NaN,S
841,842,0,2,"Mudd, Mr. Thomas Charles",male,16.00,0,0,S.O./P.P. 3,10.5000,NaN,S
843,844,0,3,"Lemberopolous, Mr. Peter L",male,34.50,0,0,2683,6.4375,NaN,C
844,845,0,3,"Culumovic, Mr. Jeso",male,17.00,0,0,315090,8.6625,NaN,S
845,846,0,3,"Abbing, Mr. Anthony",male,42.00,0,0,C.A. 5547,7.5500,NaN,S
847,848,0,3,"Markoff, Mr. Marin",male,35.00,0,0,349213,7.8958,NaN,C
848,849,0,2,"Harper, Rev. John",male,28.00,0,1,248727,33.0000,NaN,S
850,851,0,3,"Andersson, Master. Sigvard Harald Elias",male,4.00,4,2,347082,31.2750,NaN,S
860,861,0,3,"Hansen, Mr. Claus Peter",male,41.00,2,0,350026,14.1083,NaN,S
861,862,0,2,"Giles, Mr. Frederick Edward",male,21.00,1,0,28134,11.5000,NaN,S
864,865,0,2,"Gill, Mr. John William",male,24.00,0,0,233866,13.0000,NaN,S
867,868,0,1,"Roebling, Mr. Washington Augustus II",male,31.00,0,0,PC 17590,50.4958,A24,S
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.00,1,1,347742,11.1333,NaN,S
870,871,0,3,"Balkic, Mr. Cerin",male,26.00,0,0,349248,7.8958,NaN,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.00,0,0,695,5.0000,B51 B53 B55,S
876,877,0,3,"Gustafsson, Mr. Alfred Ossian",male,20.00,0,0,7534,9.8458,NaN,S
877,878,0,3,"Petroff, Mr. Nedelio",male,19.00,0,0,349212,7.8958,NaN,S
881,882,0,3,"Markun, Mr. Johann",male,33.00,0,0,349257,7.8958,NaN,S
883,884,0,2,"Banfield, Mr. Frederick James",male,28.00,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.00,0,0,SOTON/OQ 392076,7.0500,NaN,S
886,887,0,2,"Montvila, Rev. Juozas",male,27.00,0,0,211536,13.0000,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.00,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.00,0,0,370376,7.7500,NaN,Q

# Часть 4. Визуализация
### Вопросы по данным из датасета df, который использовался на воркшопе по визуализации.

In [683]:
import glob
from tqdm import tqdm

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

from plotly.subplots import make_subplots

In [684]:
paths_to_data = glob.glob('./COVID-19/csse_covid_19_data/csse_covid_19_daily_reports/*')
paths_to_data.remove('./COVID-19/csse_covid_19_data/csse_covid_19_daily_reports/README.md')

In [685]:
df = pd.DataFrame()

for i in tqdm(range(len(paths_to_data))):
    tmp = pd.read_csv(paths_to_data[i])
    df = df.append(tmp)

  1%|          | 2/264 [00:01<02:54,  1.50it/s]/home/azamat/bexugurov/bexugurov/lib/python3.5/site-packages/pandas/core/frame.py:6692: FutureWarning:

Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.


100%|██████████| 264/264 [02:24<00:00,  1.83it/s]

In [686]:
df.head()
df['Last_Update'].fillna(df['Last Update'], inplace=True)
df.head()

,Active,Admin2,Case-Fatality_Ratio,Combined_Key,Confirmed,Country/Region,Country_Region,Deaths,FIPS,Incidence_Rate,Last Update,Last_Update,Lat,Latitude,Long_,Longitude,Province/State,Province_State,Recovered
0,8305.0,NaN,3.650076,Afghanistan,38054.0,NaN,Afghanistan,1389.0,NaN,97.753973,NaN,2020-08-25 04:28:02,33.93911,NaN,67.709953,NaN,NaN,NaN,28360.0
1,3938.0,NaN,2.951772,Albania,8605.0,NaN,Albania,254.0,NaN,299.013135,NaN,2020-08-25 04:28:02,41.15330,NaN,20.168300,NaN,NaN,NaN,4413.0
2,11043.0,NaN,3.454537,Algeria,41858.0,NaN,Algeria,1446.0,NaN,95.454970,NaN,2020-08-25 04:28:02,28.03390,NaN,1.659600,NaN,NaN,NaN,29369.0
3,130.0,NaN,5.000000,Andorra,1060.0,NaN,Andorra,53.0,NaN,1371.901896,NaN,2020-08-25 04:28:02,42.50630,NaN,1.521800,NaN,NaN,NaN,877.0
4,1245.0,NaN,4.500450,Angola,2222.0,NaN,Angola,100.0,NaN,6.760731,NaN,2020-08-25 04:28:02,-11.20270,NaN,17.873900,NaN,NaN,NaN,877.0

Создайте признак 'date', в котором будет храниться дата (гггг-мм-дд). Постройте график зависимости количества строк от даты в этих строках. Найдите минимальное количество строк за день в датасете за период с 01.04.2020 по 31.08.2020.

Варианты:
- 1990
- 2472
- 472
- 103
- 1984

In [689]:
%config InlineBackend.figure_format = 'svg' 

#увеличим дефолтный размер графиков
from pylab import rcParams
rcParams['figure.figsize'] = 8, 5

df['date'] = pd.to_datetime(df['Last_Update']).apply(lambda x: x.date())
df['date'].value_counts().sort_index().plot()

mon_start = pd.to_datetime('42020', format='%m%Y').date()
mon_end = pd.to_datetime('3182020',format='%d%m%Y').date()

sec_df = df.loc[(df.date > mon_start) & (df.date < mon_end)]
min_m = sec_df.groupby('date').Last_Update.count().min()
print(min_m)
#df.date

103

Найдите максимальное количество строк за день в датасете за период с 01.04.2020 по 31.08.2020.

Варианты:
- 3990
- 3952
- 2472
- 5120
- 7025

In [524]:
print(sec_df.groupby('date').Last_Update.count().max())

4062

Постройте подобный график только для России. С какого числа Россия начала предоставлять информацию в разбивке по областям?

Варианты:
- 01.04.2020
- 06.04.2020
- 31.05.2020
- 01.06.2020
- 02.06.2020

In [693]:
df['Province_State'].fillna(df['Province/State'], inplace=True)
df['Country_Region'].fillna(df['Country/Region'], inplace=True)
#df[df['Country_Region'].str.startswith('R')]['Country_Region'].unique()

df_rus = df.loc[df.Country_Region.isin(['Russia','Russian Federation'])]
df_rus['date'].value_counts().sort_index().plot()

df_rus.groupby('Province_State').date.min()[0]

datetime.date(2020, 6, 2)

Постройте гистограмму ежедневного прироста подтверждённых случаев заболевания.
Когда в России был первый пик заболеваемости?

Варианты:
- 03.04.2020
- 19.04.2020
- 06.05.2020
- 12.05.2020
- 07.06.2020

In [700]:
#df.groupby('date').Confirmed.sum()#.hist()

date
2020-01-22         555.0
2020-01-23         653.0
2020-01-24         941.0
2020-01-25        1438.0
2020-01-26        2118.0
2020-01-27        2927.0
2020-01-28        5578.0
2020-01-29        6165.0
2020-01-30        8235.0
2020-01-31       10151.0
2020-02-01       12287.0
2020-02-02       16804.0
2020-02-03       19902.0
2020-02-04       24027.0
2020-02-05       27587.0
2020-02-06       30798.0
2020-02-07       34485.0
2020-02-08       37078.0
2020-02-09       40326.0
2020-02-10       42696.0
2020-02-11       44584.0
2020-02-12       45590.0
2020-02-13       60636.0
2020-02-14       66634.0
2020-02-15       69112.0
2020-02-16       71197.0
2020-02-17       73273.0
2020-02-18       75029.0
2020-02-19       75634.0
2020-02-20       77227.0
                 ...
2020-09-13    28760767.0
2020-09-14    28996626.0
2020-09-15    29192698.0
2020-09-16    29560112.0
2020-09-17    29864506.0
2020-09-18    30178287.0
2020-09-19    30501638.0
2020-09-20    30782922.0
2020-09-21    31024200.0
2020-09-22    31323187.0
2020-09-23    31602807.0
2020-09-24    31868778.0
2020-09-25    32229775.0
2020-09-26    32564619.0
2020-09-27    32842602.0
2020-09-28    33085666.0
2020-09-29    33360169.0
2020-09-30    33644292.0
2020-10-01    33970878.0
2020-10-02    34282557.0
2020-10-03    34585568.0
2020-10-04    34891390.0
2020-10-05    35153447.0
2020-10-06    35478899.0
2020-10-07    35806820.0
2020-10-08    36156074.0
2020-10-09    36515411.0
2020-10-10    36876096.0
2020-10-11    37180156.0
2020-10-12    37475173.0
Name: Confirmed, Length: 265, dtype: float64

In [556]:
df.shape

(749015, 20)

Постройте гистограммы подтверждённых случаев заболеваний в России и Бразилии, чтобы выбрать правильный ответ.

Варианты:
- В июле и августе ежедневное количество подтверждённых случаев заражения в Бразилии всегда выше, чем в России.
- В летние месяцы ежедневное количество подтверждённых случаев заражения в Бразилии впервые превзошло такой же показатель в России.
- В России более заметна недельная сезонность регистрации заболеваемости.
- В летние месяцы отсутствуют данные за несколько дней в обеих странах.
- Ни один ответ не верен.

In [701]:
df[df['Country_Region'].str.startswith('B')]['Country_Region'].unique()

array(['Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus',
       'Belgium', 'Belize', 'Benin', 'Bhutan', 'Bolivia',
       'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'Brunei',
       'Bulgaria', 'Burkina Faso', 'Burma', 'Burundi', 'Bahamas, The'],
      dtype=object)